### ISSUE TITLE
ERR_020 | FolderTest | testErrorDuplicateNameCreation

### ISSUE THREAD

**Issue by pakhomova-ev** [RedRoverSchool/JenkinsQA_2024_fall#1083]
Tests run: 411, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 955.666 sec <<< FAILURE!
testErrorDuplicateNameCreation(school.redrover.FolderTest)  Time elapsed: 0.192 sec  <<< FAILURE!
java.lang.AssertionError: expected [» A job already exists with the name ‘Freestyle projects’] but found []
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertEqualsImpl(Assert.java:150)
	at org.testng.Assert.assertEquals(Assert.java:132)
	at org.testng.Assert.assertEquals(Assert.java:656)
	at org.testng.Assert.assertEquals(Assert.java:666)
	at school.redrover.FolderTest.testErrorDuplicateNameCreation(FolderTest.java:156)

Results :

Failed tests:   testErrorDuplicateNameCreation(school.redrover.FolderTest): expected [» A job already exists with the name ‘Freestyle projects’] but found []

[log](https://github.com/RedRoverSchool/JenkinsQA_2024_fall/actions/runs/12036928714/job/33559248216)

**Comment by KorobovS** [comment]
Fix https://github.com/RedRoverSchool/JenkinsQA_2024_fall/pull/1368
