### ISSUE TITLE
ERR | CreateNewItem1Test | testCheckUniqueItemName

### ISSUE THREAD

**Issue by pakhomova-ev** [RedRoverSchool/JenkinsQA_2024_fall#1280]
Tests run: 396, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 889.252 sec <<< FAILURE!
testCheckUniqueItemName(school.redrover.CreateNewItem1Test)  Time elapsed: 0.199 sec  <<< FAILURE!
java.lang.AssertionError: expected [» A job already exists with the name ‘CreateNewItem’] but found []
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertEqualsImpl(Assert.java:150)
	at org.testng.Assert.assertEquals(Assert.java:132)
	at org.testng.Assert.assertEquals(Assert.java:656)
	at org.testng.Assert.assertEquals(Assert.java:666)
	at school.redrover.CreateNewItem1Test.testCheckUniqueItemName(CreateNewItem1Test.java:37)

Results :

Failed tests:   testCheckUniqueItemName(school.redrover.CreateNewItem1Test): expected [» A job already exists with the name ‘CreateNewItem’] but found []

[log](https://github.com/RedRoverSchool/JenkinsQA_2024_fall/actions/runs/12116024671/job/33775575194)

**Comment by KorobovS** [comment]
Fix 
PR https://github.com/RedRoverSchool/JenkinsQA_2024_fall/pull/1348 
commit https://github.com/RedRoverSchool/JenkinsQA_2024_fall/pull/1348/commits/e30a0f0bbb238cf811a7c8df39d397a3fb38367f
