### ISSUE TITLE
ERR|FreestyleProjectTest|testDeleteLastBuild

### ISSUE THREAD

**Issue by NatashaShimkiv** [RedRoverSchool/JenkinsQA_2024_fall#1599]
Tests run: 318, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 749.903 sec <<< FAILURE!
testDeleteLastBuild(school.redrover.FreestyleProjectTest)  Time elapsed: 6.314 sec  <<< FAILURE!
org.openqa.selenium.StaleElementReferenceException: stale element reference: stale element not found
  (Session info: chrome=131.0.6778.108)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: '4.26.0', revision: '8ccf0219d7'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.8.0-1017-azure', java.version: '17.0.13'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [a750cfe44065414cf737bbe64ed935e4, clickElement {id=f.21181B6D186FBC4A8747A7321138ED64.d.0CDE96D4B16DD7AD324551B7DB5FCC74.e.331}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.108, chrome: {chromedriverVersion: 131.0.6778.87 (ce31cae94873..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:38071}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:38071/devtoo..., se:cdpVersion: 131.0.6778.108, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on linux (a750cfe44065414cf737bbe64ed935e4)] -> xpath: //span[contains(text(), 'Delete build')]/..]
Session ID: a750cfe44065414cf737bbe64ed935e4
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:76)
	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
	at jdk.proxy2/jdk.proxy2.$Proxy25.click(Unknown Source)
	at school.redrover.page.freestyle.FreestyleBuildPage.clickDeleteBuildSidebar(FreestyleBuildPage.java:100)
	at school.redrover.FreestyleProjectTest.testDeleteLastBuild(FreestyleProjectTest.java:308)

**Comment by kas-113** [comment]
Fixed in PR https://github.com/RedRoverSchool/JenkinsQA_2024_fall/pull/1613
