### ISSUE TITLE
ERR_002 | AnyExistingItemConfigureTest | testExistingFolderConfiguration

### ISSUE THREAD

**Issue by SergeiDemyanenko** [RedRoverSchool/JenkinsQA_2024_fall#784]
Tests run: 353, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 886.403 sec <<< FAILURE!
testExistingFolderConfiguration(school.redrover.AnyExistingItemConfigureTest)  Time elapsed: 5.743 sec  <<< FAILURE!
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: //*[@id='tasks']/div[2]/span/a (tried for 5 second(s) with 500 milliseconds interval)
Build info: version: '4.26.0', revision: '8ccf0219d7'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-1025-azure', java.version: '17.0.13'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.69, chrome: {chromedriverVersion: 131.0.6778.69 (77e2244bbcda..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:45555}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:45555/devtoo..., se:cdpVersion: 131.0.6778.69, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 47516af71e82b86cf7e24396a6dae6ea
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
	at school.redrover.AnyExistingItemConfigureTest.testExistingFolderConfiguration(AnyExistingItemConfigureTest.java:22)

Results :

Failed tests:   testExistingFolderConfiguration(school.redrover.AnyExistingItemConfigureTest): Expected condition failed: waiting for visibility of element located by By.xpath: //*[@id='tasks']/div[2]/span/a (tried for 5 second(s) with 500 milliseconds interval)(..)

https://github.com/RedRoverSchool/JenkinsQA_2024_fall/pull/781

**Comment by PavelSZh** [comment]
The fix has been merged
