### ISSUE TITLE
ERR_003 | PipelineText | testCreateWithNotUniqueName

### ISSUE THREAD

**Issue by evgnick** [RedRoverSchool/JenkinsQA_2024_fall#802]
LOG: 
Tests run: 358, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 904.559 sec <<< FAILURE!
testCreateWithNotUniqueName(school.redrover.PipelineTest)  Time elapsed: 1.171 sec  <<< FAILURE!
java.lang.AssertionError: expected [» A job already exists with the name ‘ProjectUnique’] but found []
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertEqualsImpl(Assert.java:150)
	at org.testng.Assert.assertEquals(Assert.java:132)
	at org.testng.Assert.assertEquals(Assert.java:656)
	at org.testng.Assert.assertEquals(Assert.java:666)
	at school.redrover.PipelineTest.testCreateWithNotUniqueName(PipelineTest.java:115)

Results :

Failed tests:   testCreateWithNotUniqueName(school.redrover.PipelineTest): expected [» A job already exists with the name ‘ProjectUnique’] but found []

[Ссылка](https://github.com/RedRoverSchool/JenkinsQA_2024_fall/actions/runs/11940723205/job/33284785358)
[add test delete by chevron on dashboard - AT_02.005.02 #1750](https://github.com/RedRoverSchool/JenkinsQA_2024_fall/actions/runs/11974079585/job/33384391227)

**Comment by pakhomova-ev** [comment]
add wait

**Comment by pakhomova-ev** [comment]
https://github.com/RedRoverSchool/JenkinsQA_2024_fall/pull/946 -> change method ExpectedConditions.presenceOfElementLocated -> ExpectedConditions.visibilityOfElementLocated
