### ISSUE TITLE
ERR_006 | StartPageTest | testCheckLinksSidePanel

### ISSUE THREAD

**Issue by AnnaLimutina** [RedRoverSchool/JenkinsQA_2024_fall#851]
testCheckLinksSidePanel(school.redrover.StartPageTest)  Time elapsed: 0.193 sec  <<< FAILURE!
java.lang.AssertionError: expected [4] but found [1]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertEqualsImpl(Assert.java:150)
	at org.testng.Assert.assertEquals(Assert.java:132)
	at org.testng.Assert.assertEquals(Assert.java:1419)
	at org.testng.Assert.assertEquals(Assert.java:1383)
	at org.testng.Assert.assertEquals(Assert.java:1429)
	at school.redrover.StartPageTest.testCheckLinksSidePanel(StartPageTest.java:69)

**Comment by ArtsiomAzaranka** [comment]
The fix has been merged

**Comment by ArtsiomAzaranka** [comment]
The fix has been merged
