### ISSUE TITLE
ERR_010 | StartPageTest | testStartPageSidePanelTaskContent

### ISSUE THREAD

**Issue by AnnaLimutina** [RedRoverSchool/JenkinsQA_2024_fall#882]
testStartPageSidePanelTaskContent(school.redrover.StartPageTest)  Time elapsed: 0.184 sec  <<< FAILURE!
java.lang.AssertionError: expected [4] but found [1]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertEqualsImpl(Assert.java:150)
	at org.testng.Assert.assertEquals(Assert.java:132)
	at org.testng.Assert.assertEquals(Assert.java:1419)
	at org.testng.Assert.assertEquals(Assert.java:1383)
	at org.testng.Assert.assertEquals(Assert.java:1429)
	at school.redrover.StartPageTest.testStartPageSidePanelTaskContent(StartPageTest.java:54)

**Comment by ArtsiomAzaranka** [comment]
The fix has been merged
